version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "7860:7860"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
